### ISSUE TITLE
[meta] Hoa Apex 3rd edition

### ISSUE THREAD

**Issue by Hywan** [hoaproject/Keynote#5]
Need slides from:
* [ ] @pierrejoye (in PDF),
* [ ] @Hywan (in HTML),
* [ ] @osaris (in HTML),
* [ ] @K-Phoen (in HTML).

For HTML, please, do a PR. For PDF, please, attach it directly in this issue.

Thanks!

**Comment by vonglasow** [comment]
I think we can close this issue. ping @Hywan

**Comment by Hywan** [comment]
Nop. It's still not done…
